# Generated by Django 5.2.8 on 2026-04-21 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_options_package_notes_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['package', 'installment_number']},
        ),
        migrations.AddField(
            model_name='installment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('zelle', 'Zelle'), ('cash', 'Cash')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='installment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='packages.package'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('package', 'installment_number'), name='unique_installment_number_per_package'),
        ),
    ]
