# Generated by Django 5.2.8 on 2026-04-21 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_id'),
        ('packages', '0003_alter_package_options_package_notes_and_more'),
        ('sessions_app', '0003_alter_session_duration_minutes_alter_session_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['scheduled_date', 'scheduled_time']},
        ),
        migrations.AlterField(
            model_name='session',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='packages.package'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], default='scheduled', max_length=20),
        ),
    ]
