# Generated by Django 5.2.8 on 2026-04-21 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_id'),
        ('packages', '0002_alter_package_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='package',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('single', 'Single'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='single', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('zelle', 'Zelle'), ('cash', 'Cash')], default='cash', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='package',
            name='installment_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='package',
            name='sessions_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='total_sessions',
            field=models.PositiveIntegerField(),
        ),
    ]
